apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-wrapper
  name: helm-wrapper
#  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-wrapper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helm-wrapper
    spec:
      serviceAccountName: helm-wrapper
      imagePullSecrets:
        - name: csp.docker.iec.io
      containers:
        - image: csp.docker.iec.io/helm-wrapper:v1.1
          imagePullPolicy: IfNotPresent
          name: helm-wrapper
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
            - name: helm-wrapper
              containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
